# .streamlit/secrets.toml

openai_api_key = "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"
